export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCES = 'PRODUCT_LIST_SUCCES'
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCES = 'PRODUCT_DETAILS_SUCCES'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCES = 'PRODUCT_DELETE_SUCCES'
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCES = 'PRODUCT_CREATE_SUCCES'
export const PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCES = 'PRODUCT_UPDATE_SUCCES'
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCES = 'PRODUCT_CREATE_REVIEW_SUCCES'
export const PRODUCT_CREATE_REVIEW_FAILED = 'PRODUCT_CREATE_REVIEW_FAILED'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCES = 'PRODUCT_TOP_SUCCES'
export const PRODUCT_TOP_FAILED = 'PRODUCT_TOP_FAILED'