export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCES = "USER_LOGIN_SUCCES"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCES = "USER_REGISTER_SUCCES"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCES = "USER_DETAILS_SUCCES"
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_SUCCES = "USER_DUPDATE_PROFILE_SUCCES"
export const USER_UPDATE_PROFILE_FAILED = "USER_UPDATE_PROFILE_FAILED"
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCES = "USER_LIST_SUCCES"
export const USER_LIST_FAILED = "USER_LIST_FAILED"
export const USER_LIST_RESET = "USER_LIST_RESET"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCES = "USER_DELETE_SUCCES"
export const USER_DELETE_FAILED = "USER_DELETE_FAILED"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCES = "USER_UPDATE_SUCCES"
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"