export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCES = "USER_LOGIN_SUCCES"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCES = "USER_REGISTER_SUCCES"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCES = "USER_DETAILS_SUCCES"
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_SUCCES = "USER_DUPDATE_PROFILE_SUCCES"
export const USER_UPDATE_PROFILE_FAILED = "USER_UPDATE_PROFILE_FAILED"
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"